language: python

sudo: required

services:
- docker

python:
- 3.5
- 3.5-dev
- 3.6
- 3.6-dev
- 3.7-dev
- nightly

env:
- SINGVER=2.4.6

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq python dh-autoreconf squashfs-tools build-essential
- npm install jsonlint -g 
- wget https://github.com/singularityware/singularity/releases/download/$SINGVER/singularity-$SINGVER.tar.gz
- tar xvf singularity-$SINGVER.tar.gz
- cd singularity-$SINGVER
- ./configure --prefix=/usr/local --sysconfdir=/etc
- make
- sudo make install
- singularity --version
- cat /etc/singularity/singularity.conf
- cd ${TRAVIS_BUILD_DIR}/examples/
- docker pull bids/example
- docker run -v /var/run/docker.sock:/var/run/docker.sock -v ${HOME}:/output --privileged -t --rm singularityware/docker2singularity bids/example  1> ${HOME}/convert_log.txt
- IMGNAME=$(cat ${HOME}/convert_log.txt  | grep "Done. Image can be found at:" | awk '{ print $7 }' | cut -d / -f 3 | cut -d . -f 1)
- mv ${HOME}/${IMGNAME}.img ./bids-example.simg

install:
- pip install --upgrade setuptools
- pip install coveralls pytest pytest-runner
- pip install -e .

script:
- clowdr -h
- pycodestyle --max-line-length=80 clowdr/*.py clowdr/tests/*.py
- coverage run --source clowdr setup.py pytest

after_success:
- coveralls

# deploy:
# - docker push clowdr/clowdr
