language: python

sudo: required

services:
- docker

python:
- 3.5
- 3.5-dev
- 3.6
- 3.6-dev
- 3.7-dev
- nightly

before_install:
- docker build -t clowdr/clowdr .

install:
- pip install --upgrade setuptools
- pip install coveralls pytest pytest-runner
- pip install -e .

script:
- pycodestyle --max-line-length=80 clowdr/*.py clowdr/tests/*.py
- coverage run --source clowdr setup.py pytest

# after_success:
# - coveralls

# deploy:
# - docker push clowdr/clowdr
