language: python

sudo: required

services:
- docker

python:
- 3.6
- 3.6-dev
- 3.7-dev
- nightly

env:
- SINGVER=3.5.2

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq python dh-autoreconf squashfs-tools build-essential
- npm install jsonlint -g 
- cd ${HOME}
- wget https://github.com/sylabs/singularity/releases/download/v${SINGVER}/singularity-${SINGVER}.tar.gz
- tar xvf singularity-$SINGVER.tar.gz
- cd singularity
- ./mconfig
- make -C builddir
- sudo make -C builddir install
- singularity --version
- cat /etc/singularity/singularity.conf
- cd ${TRAVIS_BUILD_DIR}/examples/bids-example/
- docker pull bids/example
- docker run -v /var/run/docker.sock:/var/run/docker.sock -v ${HOME}:/output --privileged -t --rm singularityware/docker2singularity --name bids-example bids/example 1> ${HOME}/convert_log.txt
- cat ${HOME}/convert_log.txt
- ls ${HOME}
- mv ${HOME}/bids-example.simg ./bids-example.simg
- pip install --upgrade attrs
- pip install awscli
- sudo mkdir -p /data/ds114 && sudo chmod -R 777 /data/
- cd /data/ds114/
- aws s3 cp --no-sign-request --recursive --exclude "*func/*" --exclude "*dwi/*" s3://openneuro/ds000114/ds000114_R2.0.1/uncompressed/ ./
- cd ${TRAVIS_BUILD_DIR}/

install:
- pip install --upgrade setuptools
- pip install coveralls pytest pytest-runner pycodestyle
- pip install -e .

script:
- clowdr -h
# Pycodestyle command set to ignore scripts where line lengths are unavoidable,
# and maintain the normal list of ignored formatting details +E402 (top file import)
- pycodestyle --max-line-length=80 
  clowdr/*.py 
  clowdr/endpoint/*.py 
  clowdr/share/*.py 
  clowdr/tests/*.py 
  --exclude=customDash.py,AWS.py 
  --ignore=E121,E123,E126,E226,E24,E704,W503,W504,E402
- coverage run --source clowdr setup.py pytest
- coverage report -m

after_success:
- coveralls

